name: Develop CI $ CD

on:
  # Triggers the workflow on every push to develop
  push:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # First step run unit test
  test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 21, 23, 30 ]
        target: [ default ]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Copy  gradle properties file
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run detekt
        run: ./gradlew detekt

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Unit test Reports
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
        with:
          name: reports
          path: app/build/test-results

  #Build debug and upload apk to Firebase app distribution
  build_and_distribution:
    name: Upload apk to App Tester
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Copy gradle properties file
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build the app (Debug)
        run: ./gradlew assembleDebug

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: 1:300526789088:android:6724aaaa7fce58fd624b85
          token: 1//03fyZZND1kDbsCgYIARAAGAMSNwF-L9Irm1bbdpQN6cHomxHu_0_AWPzRHKDomQ2S5vs_ARJF2us9Il6yfl9suCeVU8QsnjXuUOo
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: debug apk
          path: app/build/outputs/apk/debug/app-debug.apk